modLoader="javafml"
loaderVersion="[47,)"
license="CC0-1.0"

[properties]
"connector:placeholder"=true

[[mods]]
modId="terrainslabs"
version="2.2.4"
displayName="Countered's Terrain Slabs"
authors="Countered, Souldbminer"
description='''A Minecraft mod designed to smooth out terrain using custom slabs, improving the world generation and overall feel.'''

[[dependencies.terrainslabs]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.terrainslabs]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.terrainslabs]]
modId="connector"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"