modLoader="javafml"
loaderVersion="[1,)"
license="CC0-1.0"

[properties]
"connector:placeholder"=true

[[mods]]
modId="terrainslabs"
version="2.1.2"
displayName="Countered's Terrain Slabs"
authors="Countered"
description='''A Minecraft mod designed to smooth out terrain using custom slabs, improving the world generation and overall feel.'''

[[dependencies.terrainslabs]]
modId="neoforge"
mandatory=true
versionRange="[1,)"
ordering="NONE"
side="BOTH"

[[dependencies.terrainslabs]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.terrainslabs]]
modId="connector"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"